# Generated by Django 4.1.7 on 2023-02-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matatu', '0002_vehicle_sacco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='seat_capacity',
            field=models.CharField(choices=[('11', '11'), ('14', '14')], max_length=30),
        ),
    ]
