# Generated by Django 4.1.7 on 2023-02-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matatu', '0003_alter_vehicle_seat_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='reg_no',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
