# Generated by Django 4.1.7 on 2023-02-28 12:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matatu', '0004_alter_vehicle_reg_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField(max_length=15)),
                ('status', models.CharField(choices=[('Full', 'Full'), ('Chance', 'Chance')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('gps_x', models.FloatField(max_length=15)),
                ('gps_y', models.FloatField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 2, 28, 12, 20, 11, 18213, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 2, 28, 12, 20, 11, 18213, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 2, 28, 12, 20, 11, 18213, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='price',
            field=models.FloatField(max_length=15),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='Cordinates_activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gps_x', models.FloatField(max_length=15)),
                ('gps_y', models.FloatField(max_length=15)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matatu.activity')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='direction_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matatu.town'),
        ),
        migrations.AddField(
            model_name='activity',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matatu.vehicle'),
        ),
    ]
